spring.profiles.active: uat
---
spring:
  profiles: dev
server:
  port: 8090
spring.main.lazy-initialization: false
---
spring:
  profiles: uat
server:
  port: 9090
projectdetails:
  name: demo
  version: 1.0
  duration: 22
primarydetails:
  age: 27
  gender: male
  experience: 6
